# Generated by Django 2.2.1 on 2019-05-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='image',
            field=models.FileField(default='SOME STRING', upload_to='images/'),
        ),
    ]
