# Generated by Django 2.2.1 on 2019-05-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0002_diary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
